# Generated by Django 3.0.2 on 2020-01-21 07:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Updates', '0003_auto_20200121_1322'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DUpdate',
            new_name='Update',
        ),
    ]
