# Generated by Django 3.0.2 on 2020-01-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Updates', '0004_auto_20200121_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='integer_field',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
